"""empty message

Revision ID: 960e1fe0fffe
Revises: 
Create Date: 2024-01-18 17:07:17.511933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960e1fe0fffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('apellido', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
